### ISSUE TITLE
Missing word and rule for word "ovan"

### ISSUE THREAD

**Issue by juricb** [spideyfusion/elasticsearch-croatian#1]
Word "ovan" is missing, as well as a rule that would work well with that word.

**Comment by spideyfusion** [comment]
There is actually a dictionary entry for the word `ovan`, it's just missing an affix rule:

https://github.com/spideyfusion/elasticsearch-croatian/blob/master/dict/hr_HR.dic#L29179

You could request the source dictionary to be updated so we don't end up maintaining multiple versions of it: [krunose/hr-hunspell](https://github.com/krunose/hr-hunspell)

**Comment by juricb** [comment]
You are right. I see.
I will ask over there, thank you.
