### ISSUE TITLE
Cannot install the plugin

### ISSUE THREAD

**Issue by duytech** [spideyfusion/elasticsearch-croatian#4]
Hi Petar,

I'm using ElasticSearch 7.1. I don't understand your installing instruction so I try this way.
elasticsearch-plugin install https://github.com/spideyfusion/elasticsearch-croatian/releases/download/v2.3.0/elasticsearch-croatian-v2.3.0.zip
But it failed.
![image](https://user-images.githubusercontent.com/3163862/59028917-12453a00-8887-11e9-848e-b9a06213d4ce.png)

Could you help?

**Comment by eyalzek** [comment]
This is not actually a plugin so it needs to be installed by extracting the files to the correct path, e.g:

```
RUN wget -qO /tmp/elasticsearch-croatian.zip \
    https://github.com/spideyfusion/elasticsearch-croatian/releases/download/v2.3.0/elasticsearch-croatian-v2.3.0.zip && \
    mkdir -p config/hunspell/hr_HR && \
    unzip /tmp/elasticsearch-croatian.zip -d config/hunspell/hr_HR && \
    rm /tmp/elasticsearch-croatian.zip
```

**Comment by spideyfusion** [comment]
@eyalzek You are correct. I'm gonna close this issue now due to inactivity.

Also, I added Elasticsearch 7.x testing target to Travis CI just so we can verify that the dictionary works with it.
